/* eslint-disable import/extensions */
import Head from "next/head";
import React from "react";
import Link from "next/link";

function Home() {
  return (
    <div>
      <Head>
        <title>CalculadoraDeEncontros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main color="Black">
        <Link href="/search">Click</Link>
      </main>
    </div>
  );
}

export default Home;
